import { Metadata } from "next";
import StoreProvider from "@/components/store-provider";

export const metadata: Metadata = {
  title: "Shows Detail",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <StoreProvider>{children}</StoreProvider>
    </>
  );
}
